import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/store-provider";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";

import { auth } from "@/auth";

import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <NextTopLoader />
          <Toaster richColors />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
