export const sidebarNav=[
    {
        name:"Dashboard",
        href:"/dashboard",
        isSuperAdmin:false,
        isAdmin:false,
    },
    {
        name:"Admins",
        href:"/admins",
        isSuperAdmin:true,
        isAdmin:true,
    },
    {
        name:"Questions",
        href:"/questions",
        isSuperAdmin:true,
        isAdmin:true,
    },
    {
        name:"Projects",
        href:"/projects",
        isSuperAdmin:true,
        isAdmin:false,
    },
    {
        name:"Files",
        href:"/files",
        isSuperAdmin:true,
        isAdmin:false,
    },
]