export const sidebarNav=[
    {
        name:"Dashboard",
        href:"/dashboard",
        isSuperAdmin:true,
        isAdmin:true,
        isSubAdmin:true,
    },
    {
        name:"Admins",
        href:"/admins",
        isSuperAdmin:true,
        isAdmin:true,
        isSubAdmin:false,
    },
    {
        name:"Category",
        href:"/category",
        isSuperAdmin:true,
        isAdmin:true,
        isSubAdmin:false,
    },
    {
        name:"SubCategory",
        href:"/sub-category",
        isSuperAdmin:true,
        isAdmin:true,
        isSubAdmin:false,
    },
    {
        name:"QuestionType",
        href:"/question-type",
        isSuperAdmin:true,
        isAdmin:true,
        isSubAdmin:false,
    },
    {
        name:"Questions",
        href:"/questions",
        isSuperAdmin:true,
        isAdmin:true,
        isSubAdmin:true,

    },
    {
        name:"Projects",
        href:"/projects",
        isSuperAdmin:true,
        isAdmin:false,
        isSubAdmin:false,

    },
    {
        name:"Files",
        href:"/files",
        isSuperAdmin:true,
        isAdmin:true,
        isSubAdmin:true,

    },

]